# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flows.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66lows.proto\x12\tns3_proto\"\x90\x01\n\x04\x46low\x12\x0f\n\x07srcNode\x18\x01 \x01(\r\x12\x0f\n\x07srcPort\x18\x02 \x01(\r\x12\x0f\n\x07\x64stNode\x18\x03 \x01(\r\x12\x0f\n\x07\x64stPort\x18\x04 \x01(\r\x12\x0c\n\x04size\x18\x05 \x01(\r\x12\x12\n\narriveTime\x18\x06 \x01(\r\x12\x15\n\x08priority\x18\x07 \x01(\rH\x00\x88\x01\x01\x42\x0b\n\t_priority\"\'\n\x05\x46lows\x12\x1e\n\x05\x66lows\x18\x01 \x03(\x0b\x32\x0f.ns3_proto.Flowb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flows_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOW._serialized_start=27
  _FLOW._serialized_end=171
  _FLOWS._serialized_start=173
  _FLOWS._serialized_end=212
# @@protoc_insertion_point(module_scope)
